### ISSUE TITLE
[is_5ghz_supported] function is not detectable in Kali Linux in M1 vmware

### ISSUE THREAD

**Issue by pavnguyen** [martin-olivier/airgorah#120]
Hi,

I'm always using my usb that supports 5ghz for sure.

Actually, I'm using M1 with vmware to run kali linux but I think fn is_5ghz_supported(iface: &str) function (v 0.7.2) doesn't work with the current code.

```
/// Check if an interface supports 5GHz
pub fn is_5ghz_supported(iface: &str) -> Result<bool, IfaceError> {
    let phy_path = format!("/sys/class/net/{}/phy80211", iface);
```

```
┌──(kali㉿kali)-[~]
└─$ iw list | grep 5200  
                        * 5200.0 MHz [40] (20.0 dBm)
                        * 5200.0 MHz [40] (20.0 dBm)
                        * 5200.0 MHz [40] (20.0 dBm)
```

I have 3 usb that support 5GHZ.

Please check it, or you can always turn on (check it by default 5ghz option like 2.4ghz, and try catch) to avoid some stucks.

Thanks @martin-olivier

**Comment by pavnguyen** [comment]
FYI: I've changed some code to check 5ghz by default in FE and changes some small modifs in BE and rebuild and it works.

**Comment by Romko666** [comment]
I can’t get the ASUS USB-AC56 adapter to work at 5 GHz, it’s dual-band and it can definitely work at 5 GHz (for example wifite). 
How can I switch from 2.4 to 5?

└─# iw list | grep 5200
                        * 5200.0 MHz [40] (30.0 dBm)

**Comment by martin-olivier** [comment]
Hello @pavnguyen and @Romko666,

Mhhh, that's strange, it is working fine on my 5ghz USB antenna.

> Do you have an error window after interface selection ?

> Do you know witch line is returning `Ok(false)` or `Err(...)` inside `is_5ghz_supported` function ?

**Comment by pavnguyen** [comment]
@martin-olivier 

I have not the error after interface selection, but I can not check the 5ghz checkbox.

**Comment by Romko666** [comment]
There are no errors when selecting 5GHz, but the checkbox is not selected either. How it looks on the screenshot.
Attached is a log of how the program is loaded.

[airgorah.txt](https://github.com/martin-olivier/airgorah/files/15186392/airgorah.txt)

![image](https://github.com/martin-olivier/airgorah/assets/155727664/775bcca1-2780-4527-9418-8a4160f47247)

**Comment by martin-olivier** [comment]
Thanks for your feedback,
If the 5ghz button is not selectable, it is because the `is_5ghz_supported` function returned either `Ok(false)` or `Err(...)`
Can you tell me witch line of this function failed @pavnguyen ?

**Comment by Romko666** [comment]
> If the 5ghz button is not selectable, it is because the `is_5ghz_supported` function returned either `Ok(false)` or `Err(...)`
> Can you tell me witch line of this function failed @pavnguyen ?
If you tell me where to look at it, I’ll look at it myself.

**Comment by martin-olivier** [comment]
Thanks @Romko666,

Can you replace the code of the function `is_5ghz_supported`, located in `src/backend/interface.rs`, by the following code:

```rs
pub fn is_5ghz_supported(iface: &str) -> Result<bool, IfaceError> {
    let phy_path = format!("/sys/class/net/{}/phy80211", iface);

    let phy_link = std::fs::read_link(phy_path)?;

    log::warn!(
        "{}: PHY link is '{:?}'",
        iface,
        phy_link
    );

    let phy_name = match phy_link.file_name() {
        Some(name) => name,
        None => return Err(IfaceError::PhyParsing),
    };

    log::warn!(
        "{}: PHY name is '{:?}'",
        iface,
        phy_name
    );

    let phy_name_str = match phy_name.to_str() {
        Some(name) => name,
        None => return Err(IfaceError::PhyParsing),
    };

    log::warn!(
        "{}: PHY name str is '{}'",
        iface,
        phy_name_str
    );

    let check_band_cmd = Command::new("iw")
        .args(["phy", phy_name_str, "info"])
        .output()?;

    log::warn!(
        "{}: iw binary found",
        iface
    );

    if !check_band_cmd.status.success() {
        return Err(IfaceError::PhyNotFound(phy_name_str.to_string()));
    }

    log::warn!(
        "{}: iw cmd returned 0",
        iface
    );

    let check_band_output = String::from_utf8(check_band_cmd.stdout)?;

    log::warn!(
        "{}: iw returned valid UTF8",
        iface
    );

    if check_band_output.contains("5200 MHz") {
        log::warn!(
            "{}: SUPPORTS 2.4 and 5 GHZ",
            iface
        );
        return Ok(true);
    }

    log::warn!(
        "{}: SUPPORTS only 2.4 GHZ",
        iface
    );
    Ok(false)
}
```

Then, after rebuilding, launch the software using command line and send me the logs after interface selection

**Comment by Romko666** [comment]
There were errors during assembly, the log is in the attachment.
[build.txt](https://github.com/martin-olivier/airgorah/files/15193890/build.txt)

**Comment by martin-olivier** [comment]
It is building correctly on my side.
Here is the full `src/backend/interface.rs` file:

[interface.rs.txt](https://github.com/martin-olivier/airgorah/files/15194080/interface.rs.txt)

**Comment by Romko666** [comment]
I was able to compile it with your file.
After assembly, I installed it from the deb package, but the 5GHz selection checkbox is not available, the logs say that only 2.4 is supported.
But if you look at the iw list output file, you can see that the adapter supports two bands.

[iw list output.txt](https://github.com/martin-olivier/airgorah/files/15197584/iw.list.output.txt)
[airgorah_new.txt](https://github.com/martin-olivier/airgorah/files/15197585/airgorah_new.txt)

**Comment by martin-olivier** [comment]
Thank you @Romko666,

I found why it doesn't work for you.
I fixed that in commit eb2eed92410c793009d4b408c3ebf0369ad4e523 on the `dev` branch

Can you re-clone `airgorah` from the dev branch:

```sh
git clone https://github.com/martin-olivier/airgorah.git -b dev
```

Then re-build the software, and test if the 5ghz is enabled and working.

Thanks

**Comment by Romko666** [comment]
It works!!! Now I can work with different frequencies!

![image](https://github.com/martin-olivier/airgorah/assets/155727664/daa80848-b012-4d41-af7b-dcba1cf332ee)

**Comment by martin-olivier** [comment]
Nice, thanks for your feedback!

@pavnguyen If  you have time, can you check also on the `dev` branch if it works for you and close the issue if it is the case ?
