### ISSUE TITLE
I cannot activate the 5ghz

### ISSUE THREAD

**Issue by ulises-31** [martin-olivier/airgorah#129]
One question, I cannot activate the 5ghz network option in Airgorah with an alpha antenna awus036acm

**Comment by martin-olivier** [comment]
Hello @ulises-31, thanks for reporting this issue.

Which version of `airgorah` are you using ?

**Comment by ulises-31** [comment]
V0.7.3

**Comment by ulises-31** [comment]
Wiphy phy0
        wiphy index: 0
        max # scan SSIDs: 4
        max scan IEs length: 2243 bytes
        max # sched scan SSIDs: 0
        max # match sets: 0
        Retry short limit: 7
        Retry long limit: 4
        Coverage class: 0 (up to 0m)
        Device supports RSN-IBSS.
        Device supports AP-side u-APSD.
        Device supports T-DLS.
        Supported Ciphers:
                * WEP40 (00-0f-ac:1)
                * WEP104 (00-0f-ac:5)
                * TKIP (00-0f-ac:2)
                * CCMP-128 (00-0f-ac:4)
                * CCMP-256 (00-0f-ac:10)
                * GCMP-128 (00-0f-ac:8)
                * GCMP-256 (00-0f-ac:9)
                * CMAC (00-0f-ac:6)
                * CMAC-256 (00-0f-ac:13)
                * GMAC-128 (00-0f-ac:11)
                * GMAC-256 (00-0f-ac:12)
        Available Antennas: TX 0x3 RX 0x3
        Configured Antennas: TX 0x3 RX 0x3
        Supported interface modes:
                 * IBSS
                 * managed
                 * AP
                 * AP/VLAN
                 * monitor
                 * mesh point
                 * P2P-client
                 * P2P-GO
        Band 1:
                Capabilities: 0x1ff
                        RX LDPC
                        HT20/HT40
                        SM Power Save disabled
                        RX Greenfield
                        RX HT20 SGI
                        RX HT40 SGI
                        TX STBC
                        RX STBC 1-stream
                        Max AMSDU length: 3839 bytes
                        No DSSS/CCK HT40
                Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
                Minimum RX AMPDU time spacing: No restriction (0x00)
                HT TX/RX MCS rate indexes supported: 0-15
                Bitrates (non-HT):
                        * 1.0 Mbps (short preamble supported)
                        * 2.0 Mbps (short preamble supported)
                        * 5.5 Mbps (short preamble supported)
                        * 11.0 Mbps (short preamble supported)
                        * 6.0 Mbps
                        * 9.0 Mbps
                        * 12.0 Mbps
                        * 18.0 Mbps
                        * 24.0 Mbps
                        * 36.0 Mbps
                        * 48.0 Mbps
                        * 54.0 Mbps
                Frequencies:
                        * 2412.0 MHz [1] (20.0 dBm)
                        * 2417.0 MHz [2] (20.0 dBm)
                        * 2422.0 MHz [3] (20.0 dBm)
                        * 2427.0 MHz [4] (20.0 dBm)
                        * 2432.0 MHz [5] (20.0 dBm)
                        * 2437.0 MHz [6] (20.0 dBm)
                        * 2442.0 MHz [7] (20.0 dBm)
                        * 2447.0 MHz [8] (20.0 dBm)
                        * 2452.0 MHz [9] (20.0 dBm)
                        * 2457.0 MHz [10] (20.0 dBm)
                        * 2462.0 MHz [11] (20.0 dBm)
                        * 2467.0 MHz [12] (20.0 dBm)
                        * 2472.0 MHz [13] (20.0 dBm)
                        * 2484.0 MHz [14] (20.0 dBm) (no IR)
        Band 2:
                Capabilities: 0x1ff
                        RX LDPC
                        HT20/HT40
                        SM Power Save disabled
                        RX Greenfield
                        RX HT20 SGI
                        RX HT40 SGI
                        TX STBC
                        RX STBC 1-stream
                        Max AMSDU length: 3839 bytes
                        No DSSS/CCK HT40
                Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
                Minimum RX AMPDU time spacing: No restriction (0x00)
                HT TX/RX MCS rate indexes supported: 0-15
                VHT Capabilities (0x318001b0):
                        Max MPDU length: 3895
                        Supported Channel Width: neither 160 nor 80+80
                        RX LDPC
                        short GI (80 MHz)
                        TX STBC
                        RX antenna pattern consistency
                        TX antenna pattern consistency
                VHT RX MCS set:
                        1 streams: MCS 0-9
                        2 streams: MCS 0-9
                        3 streams: not supported
                        4 streams: not supported
                        5 streams: not supported
                        6 streams: not supported
                        7 streams: not supported
                        8 streams: not supported
                VHT RX highest supported: 0 Mbps
                VHT TX MCS set:
                        1 streams: MCS 0-9
                        2 streams: MCS 0-9
                        3 streams: not supported
                        4 streams: not supported
                        5 streams: not supported
                        6 streams: not supported
                        7 streams: not supported
                        8 streams: not supported
                VHT TX highest supported: 0 Mbps
                VHT extended NSS: not supported
                Bitrates (non-HT):
                        * 6.0 Mbps
                        * 9.0 Mbps
                        * 12.0 Mbps
                        * 18.0 Mbps
                        * 24.0 Mbps
                        * 36.0 Mbps
                        * 48.0 Mbps
                        * 54.0 Mbps
                Frequencies:
                        * 5180.0 MHz [36] (20.0 dBm)
                        * 5200.0 MHz [40] (20.0 dBm)
                        * 5220.0 MHz [44] (20.0 dBm) (no IR)
                        * 5240.0 MHz [48] (20.0 dBm)
                        * 5260.0 MHz [52] (20.0 dBm) (no IR, radar
detection)
                        * 5280.0 MHz [56] (20.0 dBm) (no IR, radar
detection)
                        * 5300.0 MHz [60] (20.0 dBm) (no IR, radar
detection)
                        * 5320.0 MHz [64] (20.0 dBm) (no IR, radar
detection)
                        * 5500.0 MHz [100] (20.0 dBm) (no IR, radar
detection)
                        * 5520.0 MHz [104] (20.0 dBm) (no IR, radar
detection)
                        * 5540.0 MHz [108] (20.0 dBm) (no IR, radar
detection)
                        * 5560.0 MHz [112] (20.0 dBm) (no IR, radar
detection)
                        * 5580.0 MHz [116] (20.0 dBm) (no IR, radar
detection)
                        * 5600.0 MHz [120] (20.0 dBm) (no IR, radar
detection)
                        * 5620.0 MHz [124] (20.0 dBm) (no IR, radar
detection)
                        * 5640.0 MHz [128] (20.0 dBm) (no IR, radar
detection)
                        * 5660.0 MHz [132] (20.0 dBm) (no IR, radar
detection)
                        * 5680.0 MHz [136] (20.0 dBm) (no IR, radar
detection)
                        * 5700.0 MHz [140] (20.0 dBm) (no IR, radar
detection)
                        * 5720.0 MHz [144] (20.0 dBm) (no IR, radar
detection)
                        * 5745.0 MHz [149] (20.0 dBm) (no IR)
                        * 5765.0 MHz [153] (20.0 dBm) (no IR)
                        * 5785.0 MHz [157] (20.0 dBm) (no IR)
                        * 5805.0 MHz [161] (20.0 dBm) (no IR)
                        * 5825.0 MHz [165] (20.0 dBm) (no IR)
                        * 5845.0 MHz [169] (disabled)
                        * 5865.0 MHz [173] (disabled)
                        * 5885.0 MHz [177] (disabled)
        Supported commands:
                 * new_interface
                 * set_interface
                 * new_key
                 * start_ap
                 * new_station
                 * new_mpath
                 * set_mesh_config
                 * set_bss
                 * authenticate
                 * associate
                 * deauthenticate
                 * disassociate
                 * join_ibss
                 * join_mesh
                 * remain_on_channel
                 * set_tx_bitrate_mask
                 * frame
                 * frame_wait_cancel
                 * set_wiphy_netns
                 * set_channel
                 * tdls_mgmt
                 * tdls_oper
                 * probe_client
                 * set_noack_map
                 * register_beacons
                 * start_p2p_device
                 * set_mcast_rate
                 * connect
                 * disconnect
                 * channel_switch
                 * set_qos_map
                 * set_multicast_to_unicast
                 * set_sar_specs
        software interface modes (can always be added):
                 * AP/VLAN
                 * monitor
        valid interface combinations:
                 * #{ IBSS } <= 1, #{ managed, AP, mesh point, P2P-client,
P2P-GO } <= 2,
                   total <= 2, #channels <= 1, STA/AP BI must match
        HT Capability overrides:
                 * MCS: ff ff ff ff ff ff ff ff ff ff
                 * maximum A-MSDU length
                 * supported channel width
                 * short GI for 40 MHz
                 * max A-MPDU length exponent
                 * min MPDU start spacing
        Device supports TX status socket option.
        Device supports HT-IBSS.
        Device supports SAE with AUTHENTICATE command
        Device supports low priority scan.
        Device supports scan flush.
        Device supports AP scan.
        Device supports per-vif TX power setting
        Driver supports full state transitions for AP/GO clients
        Driver supports a userspace MPM
        Device supports active monitor (which will ACK incoming frames)
        Driver/device bandwidth changes during BSS lifetime (AP/GO mode)
        Device supports configuring vdev MAC-addr on create.
        max # scan plans: 1
        max scan plan interval: -1
        max scan plan iterations: 0
        Supported TX frame types:
                 * IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90
0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80
0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90
0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80
0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * mesh point: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80
0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80
0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80
0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-device: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80
0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
        Supported RX frame types:
                 * IBSS: 0x40 0xb0 0xc0 0xd0
                 * managed: 0x40 0xb0 0xd0
                 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * mesh point: 0xb0 0xc0 0xd0
                 * P2P-client: 0x40 0xd0
                 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * P2P-device: 0x40 0xd0
        Supported extended features:
                * [ VHT_IBSS ]: VHT-IBSS
                * [ RRM ]: RRM
                * [ FILS_STA ]: STA FILS (Fast Initial Link Setup)
                * [ CQM_RSSI_LIST ]: multiple CQM_RSSI_THOLD records
                * [ CONTROL_PORT_OVER_NL80211 ]: control port over nl80211
                * [ TXQS ]: FQ-CoDel-enabled intermediate TXQs
                * [ SCAN_RANDOM_SN ]: use random sequence numbers in scans
                * [ SCAN_MIN_PREQ_CONTENT ]: use probe request with only
rate IEs in scans
                * [ AIRTIME_FAIRNESS ]: airtime fairness scheduling
                * [ AQL ]: Airtime Queue Limits (AQL)
                * [ CONTROL_PORT_NO_PREAUTH ]: disable pre-auth over
nl80211 control port support
                * [ DEL_IBSS_STA ]: deletion of IBSS station support
                * [ SCAN_FREQ_KHZ ]: scan on kHz frequency support
                * [ CONTROL_PORT_OVER_NL80211_TX_STATUS ]: tx status for
nl80211 control port support
                * [ POWERED_ADDR_CHANGE ]: can change MAC address while up

**Comment by martin-olivier** [comment]
@ulises-31 

Since `5200.0 MHz` is present in your output and `airgorah` is doing the same steps as in the shell script I provided to check if 5ghz is supported, I think you are running a version lower than `0.7.3`.

I fixed a bug in latest version to check both `5200.0 MHz` and `5200 MHz` in the `iw phy XXX info` command output to define if 5ghz is supported:

- fix commit
https://github.com/martin-olivier/airgorah/commit/eb2eed92410c793009d4b408c3ebf0369ad4e523

- linked issue
https://github.com/martin-olivier/airgorah/issues/120

Can you re-check that your are running `v0.7.3` ?

![Screenshot from 2024-05-15 00-34-02](https://github.com/martin-olivier/airgorah/assets/58467105/a9647f7d-7746-4901-84b3-987af227fdd8)

**Comment by martin-olivier** [comment]
@ulises-31 

Didn't see your answer

**Comment by ulises-31** [comment]
Hay una captura. La version es 0.7.3

**Comment by martin-olivier** [comment]
@ulises-31

Can you replace the code of the function `is_5ghz_supported`, located in `src/backend/interface.rs`, by the following code:

```rs
pub fn is_5ghz_supported(iface: &str) -> Result<bool, IfaceError> {
    let phy_path = format!("/sys/class/net/{}/phy80211", iface);

    let phy_link = std::fs::read_link(phy_path)?;

    log::warn!(
        "{}: PHY link is '{:?}'",
        iface,
        phy_link
    );

    let phy_name = match phy_link.file_name() {
        Some(name) => name,
        None => return Err(IfaceError::PhyParsing),
    };

    log::warn!(
        "{}: PHY name is '{:?}'",
        iface,
        phy_name
    );

    let phy_name_str = match phy_name.to_str() {
        Some(name) => name,
        None => return Err(IfaceError::PhyParsing),
    };

    log::warn!(
        "{}: PHY name str is '{}'",
        iface,
        phy_name_str
    );

    let check_band_cmd = Command::new("iw")
        .args(["phy", phy_name_str, "info"])
        .output()?;

    log::warn!(
        "{}: iw binary found",
        iface
    );

    if !check_band_cmd.status.success() {
        return Err(IfaceError::PhyNotFound(phy_name_str.to_string()));
    }

    log::warn!(
        "{}: iw cmd returned 0",
        iface
    );

    let check_band_output = String::from_utf8(check_band_cmd.stdout)?;

    log::warn!(
        "{}: iw returned valid UTF8",
        iface
    );

    if check_band_output.contains("5200 MHz") {
        log::warn!(
            "{}: SUPPORTS 2.4 and 5 GHZ",
            iface
        );
        return Ok(true);
    }

    log::warn!(
        "{}: SUPPORTS only 2.4 GHZ",
        iface
    );
    Ok(false)
}
```

Then rebuild the project:

```sh
cargo build
```

Then launch the software using command line:

```sh
sudo ./target/debug/airgorah
```

And send me the logs after interface selection

**Comment by ulises-31** [comment]
no encuentro el directorio ni el fichero a editar

src/backend/interface.rs,

**Comment by ulises-31** [comment]
I need docker?

**Comment by martin-olivier** [comment]
Not nessesary,

To build the project you need to:

Install rust compiler: https://www.rust-lang.org/tools/install

download dependencies:

```sh
sudo apt install -y build-essential libgtk-4-dev libglib2.0-dev aircrack-ng wireshark-common
```

And then, clone and launch a terminal inside `airgorah` repo and build with the following command:

```sh
cargo build
```

Then launch the software:

```sh
sudo ./target/debug/airgorah
```

**Comment by ulises-31** [comment]
He actualizado Kali linux y se ha solucionado el problemas. Muchísimas
gracias por ayudarme. Un saludo
