### ISSUE TITLE
Change service to systemctl is more generic

### ISSUE THREAD

**Issue by pavnguyen** [martin-olivier/airgorah#25]
Hello @martin-olivier,

I think you can improve this app by replacing "service' by 'systemctl' to handle the services. It's more generic than "service" because service is a Ubuntu's command, I guess. But for others distro systemd, it works with systemctl command.

```rust
    Command::new("service")
        .args(["NetworkManager", "restart"])
        .output()?;
    Command::new("service")
        .args(["network-manager", "restart"])
        .output()?;
    Command::new("service")
        .args(["wpa-supplicant", "restart"])
        .output()?;
``` 

Thanks.

**Comment by martin-olivier** [comment]
Hello @pavnguyen,

Thanks for noticing that, I forgot that `service` was deprecated.

I have implemented your requested change on https://github.com/martin-olivier/airgorah/commit/2a424e2bce07797ba272b8eb61899c9125e40295 and tested it.

**Comment by martin-olivier** [comment]
Merged into [dev](https://github.com/martin-olivier/airgorah/tree/dev) as https://github.com/martin-olivier/airgorah/commit/52c8caf42f402dc959af7a4858546831c2fbb256
