### ISSUE TITLE
UI  & feature issue

### ISSUE THREAD

**Issue by pavnguyen** [martin-olivier/airgorah#5]
Bonjour,

J'ai quelques problemes avec votre derniere version 0.3.0:
- Les colonnes GUI ne sont pas ajustable.
- Le nombre de clients connecté n'est pas correct.

Si c'est possbile, est ce que vous pourrier ajouter l'option mdk4 pour la deauth, svp?

Merci.

**Comment by martin-olivier** [comment]
Bonjour,

Merci pour votre retour.

J'ai corrigé le problème des colones sur le commit [feat: adjustable columns](https://github.com/martin-olivier/airgorah/pull/6/commits/7881c25fc1bf1b7f6b0599dad655266440792e5e).

En revanche, je n'arrive pas à reproduire le problème concernant l'affichage du nombre de clients connectés.
Pouvez-vous me transmettre des capture d'écran ou les étapes à reproduire pour que ce bug se produise ?

Concernant l'ajout de `mdk4` pour le deauth, pouvez vous ouvrir une autre issue pour cette feature ?

Merci.

**Comment by pavnguyen** [comment]
Bonjour Martin,

Merci de votre réactiviter.

1/ Concernant l'affichage du nombre de clients connectés, j'ai constaté avec mes anciens resultats et je vois la difference:
- Etape 1: activer 2.4 and 5ghz.
- Etape 2: scan

Si vous n'arrivez pas à reproduire, peut etre c'est le probleme de mon cote. Je vous tiendrais au courant des que j'arrive a reproduire.

2/ Je ferai un ticket mdk4 avec plaisir. Merci de votre aide.
