### ISSUE TITLE
Make the ESSID, BSSID, Station MAC, Vendors columns copy/pasteable

### ISSUE THREAD

**Issue by pavnguyen** [martin-olivier/airgorah#61]
Please add a feature that allows me to copy/paste data in the ESSID, BSSID and Station MAC, Vendor columns. Thanks @martin-olivier

**Comment by martin-olivier** [comment]
Hello @pavnguyen 

I just done your requested feature in 0d5d2d76ff9981e1e6f6d2c3b1f6bdacaab16b20, currently on `dev` branch.

It will be available on the next release (0.7.2)
