### ISSUE TITLE
Please add mdk4 for deauth and some features of mdk4 as a bonus option

### ISSUE THREAD

**Issue by pavnguyen** [martin-olivier/airgorah#7]
Could you please add an option that use mdk4 for deauth and mdk4 with some parameters for flooding, etc...? Thanks.

**Comment by martin-olivier** [comment]
Hello,

Sorry for the delay.
I have implemented the feature you requested on commit [c9bd668](https://github.com/martin-olivier/airgorah/commit/c9bd6689a7ece3753ecc0452620ef12832455d0b) in branch `feat/mdk4`

Do not hesitate to give me feedback.

**Comment by pavnguyen** [comment]
It works well, but could you add a parameter -c <channel>  for mdk4 channel. For example:  mdk4 wlan1 d -B XX:XX...XX **-c <channel>**

Many thanks @martin-olivier

**Comment by martin-olivier** [comment]
Hello,

I don't know a lot about `mdk4`, but referring to the manual, I dont see a use case of combining `-c` and `-B` options, since `-c` is used to enable channel hopping on selected 2.4 GHz channels and `-B` is used to specify the BSSID of the AP to deauth (witch is on a specific channel).

Can you explain me the use case of combining those two options ?

```
> sudo mdk4 --help d
  Sends deauthentication and disassociation packets to stations
  based on data traffic to disconnect all clients from an AP.
      -w <filename>
         Read file containing MACs not to care about (Whitelist mode)
      -b <filename>
         Read file containing MACs to run test on (Blacklist Mode)
      -s <pps>
         Set speed in packets per second (Default: unlimited)
      -x
         Enable full IDS stealth by matching all Sequence Numbers
         Packets will only be sent with clients' addresses
      -c [chan,chan,...,chan[:speed]]
         Enable channel hopping. When -c h is given, mdk4 will hop an all
         14 b/g channels. Channel will be changed every 3 seconds,
         if speed is not specified. Speed value is in milliseconds!
      -E <AP ESSID>
         Specify an AP ESSID to attack.
      -B <AP BSSID>
         Specify an AP BSSID to attack.
      -S <Station MAC address>
         Specify a station MAC address to attack.
      -W <Whitelist Station MAC address>
         Specify a whitelist station MAC.
```

Thanks

**Comment by martin-olivier** [comment]
Found that regarding channel option:

https://github.com/aircrack-ng/mdk4/issues/80

**Comment by pavnguyen** [comment]
@martin-olivier , I have an idea for mdk4 in case the user reset his router or change his channel, we can stop (kill) to running mdk4 and re-run a new process with new channel changed. It means we don't need to stop and relance manuellay to deauth if the user changes his channel to by pass the hopping or specify channel ( juste detect via the list from airedump-ng)

**Comment by martin-olivier** [comment]
Mhhh that is a very specific feature, I need first to refacto the code correctly and finish to implement some missing features.
Can you open another issue for that ? Thanks
