### ISSUE TITLE
Client issue

### ISSUE THREAD

**Issue by pavnguyen** [martin-olivier/airgorah#8]
Bonjour,

Je vous fais des capture d'ecran entre la version 0.1.0 et 0.3.0

Avec la version 0.1.0, j'ai trouve rapidement les clients connectes. Par contre, j'ai checkout votre dernier fix/columns-and-clients, j'ai toujours ce probleme.

![SCR-20230401-onal](https://user-images.githubusercontent.com/465613/229278138-fe1e07e4-7e08-4969-b0b3-f9fede13ef04.png)

0.1.0
![SCR-20230401-omiu](https://user-images.githubusercontent.com/465613/229278145-4bf5f83d-b2a7-4bd0-acd7-5da71d6ed213.png)

Merci.

**Comment by martin-olivier** [comment]
Bonjour,

J'ai pu essayer de mon coté mais je n'ai pas constaté de différences entre la version `0.1.0` et la version `0.3.0`.

Aviez-vous également activé la 5GHz lors de la capture de la version `0.1.0` ?

**Comment by pavnguyen** [comment]
@martin-olivier Oui, j'ai toujours activé 5GHZ lors de la capture de la version 0.1.0 et 0.3.0.

**Comment by martin-olivier** [comment]
Mhhhh,

En regardant à nouveau les changement de code sur le fichier `src/backend/scan.rs`:

Dans la fonction `set_scan_process` le seul changement notable est l'ajout de `cap` à l'argument `--output-format` afin que airodump génère en permanence un fichier de capture au cas ou un handshake est capturé.

```
    let mut proc_args = vec![
        iface.as_str(),
        "-a",
        "--output-format",
        "csv,cap",
        "-w",
        LIVE_SCAN_PATH,
        "--write-interval",
        "1",
    ];
```

Il n'y a pas de changement coté frontend sur l'appel de cette fonction et les paramètres qui lui sont donnés.

Quant à la fonction `get_airodump_data` il n'y a pas eu de changements coté parsing du fichier csv généré par airodump.

Ce problème survient il si vous sélectionnez uniquement `2.4` Ghz ?

**Comment by pavnguyen** [comment]
@martin-olivier 

Non, j'ai eu ce probleme pour les 2 cas 2.4 et 2.4 & 5 Ghz.

**Comment by martin-olivier** [comment]
@pavnguyen

J'ai fait plusieurs tests et j'ai repassé le code en revue, mais de mon coté je n'ai aucune différence sur la rapidité et les informations affichées entre la version `0.1.0` et `0.3.0`.

Sur la capture d'écran de la version `0.3.0`, votre carte réseau n'a pas l'air d'être en mode moniteur (on voit `wlan0` au lieu de `wlan0mon`). Cela pourrait peux être expliquer le manque de données récupérées
Pouvez vous vérifier cela en executant `iwconfig` après avoir lancé un scan ?

**Comment by pavnguyen** [comment]
@martin-olivier 

Je vous confirme que ma carte wlan0 est en mode monitoring, j'ai force manuellement via iwconfig mode monitor.

**Comment by martin-olivier** [comment]
Merci pour votre retour.

Sur la version `0.3.0`, le paramètre `Kill NetworkManager` est il bien activé ?

Je soupçonne l'implémentation de l'actualisation de l'affichage des handshakes capturées de causer un ralentissement conséquent, surtout dans le cas ou il y a beaucoup de hotspots aux alentours. Pouvez vous me dire si la modification suivante règle le soucis ?

Aller sur la branche `dev`:
```sh
git pull
git checkout dev
```

Commenter le code suivant situé `src/frontend/connections/app.rs` ligne `246`:
```rs
[...]

    /*glib::timeout_add_local(Duration::from_millis(1500), || {
        backend::update_handshakes().ok();

        glib::Continue(true)
    });*/
}

[...]
```

Compiler et lancer le programme:
```
cargo build
sudo ./target/debug/airgorah
```

**Comment by pavnguyen** [comment]
@martin-olivier 

It's weird

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/465613/231425729-a91b8a5b-1af6-4347-8e15-84e81d740c9a.png">

**Comment by pavnguyen** [comment]
@martin-olivier 

C'est super fluid quand je lance la commande airodump-ng -a --output-format csv,cap -w /tmp/airgorah_live_scan --write-interval 1

<img width="493" alt="image" src="https://user-images.githubusercontent.com/465613/232970029-4a12e7dc-56a3-46a4-8a72-549fc99fa275.png">

**Comment by pavnguyen** [comment]
@martin-olivier 

J'ai essaye de rebuild and changer quelques code pour adapter mon ArchLinux. Ca marche bien maintenant sur mon Arch. Peut être le probleme vient de mon Kali Linux sous Vmware. Donc je ferme ce ticket. Merci.

**Comment by martin-olivier** [comment]
Entendu, merci pour votre retour :)
