### ISSUE TITLE
mac os run????

### ISSUE THREAD

**Issue by pullghjunkkk** [martin-olivier/airgorah#81]
paulchikkkk@7ee570 ~ % git clone https://github.com/martin-olivier/airgorah.git
cd airgorah
fatal: destination path 'airgorah' already exists and is not an empty directory.
paulchikkkk@7ee570 airgorah % cargo build --release
zsh: command not found: cargo
paulchikkkk@7ee570 airgorah %

**Comment by martin-olivier** [comment]
Hello,

As written on the README, this software only works on linux.
If you have a mac, you should use an ubuntu virtual machine to run the software, and use an external USB wifi antenna.
