### ISSUE TITLE
feat: generation of void and alpine package on a release

### ISSUE THREAD

**Issue by martin-olivier** [martin-olivier/airgorah#84]
Requested in https://github.com/martin-olivier/airgorah/issues/68

**Comment by 0323pin** [comment]
I meant pinging on of the Void devs and getting it packaged by the distro but, this is also nice 😄

**Comment by martin-olivier** [comment]
Hello @0323pin,

Since the last time, I was able to download an `Artix Linux` virtual machine to be able to test the `runit` support feature of `Airgorah`.

I encountered some issues.

The argument to provide to `sudo sv down` and `sudo sv up` is the path of the service, not his name.
On my case, for example, `wpa_supplicant` is located in `/run/runit/service`

I saw on internet that the path is not a standard, it differs depending of the operating system:

> Unlike other distros using runit, Artix doesn't store its service directory in /var/service or /service , but in /run/runit/service instead.

I am thinking about droping the support of `runit` and others `non-systemd` service managers.
Since it is not as standardize as systemd, I am afraid of potential security issues that it could lead to.

What is your opinion on that ?

**Comment by 0323pin** [comment]
Hi @martin-olivier

> I encountered some issues.

That's unfortunate.

> I am thinking about droping the support of runit and others non-systemd service managers.
Since it is not as standardize as systemd, I am afraid of potential security issues that it could lead to.
What is your opinion on that ?

First of all, thanks for asking.
`airgorah` it's your project, as such, you do what ever you please. That's the point, isn't it?

But, since you've asked ...

I think, it's a pity you want to drop support for other init systems but, I would have to respect that.
In this case, please just make it clear that you only support `systemd` in the README.

I understand your point but, just to be clear, I **will never** use anything that uses `systemd`.

**Comment by martin-olivier** [comment]
Hello @0323pin,

Thanks for your feedback.

I think I found a compromise:

- Airgorah will not depend on `systemd`
- If the user is running under `systemd`, the `Kill/Restore network managers` option will be usable and enabled by default
- If not, this option will not be usable and disabled by default
- I will specify in the documentation that non-systemd users will have to manually disable network managers if they need to
- If the monitor mode activation fails, I will show on the error window the `stderr` returned by `airmon-ng start XXX` so they can easily understand what is causing the error

What is your opinion on that ?

**Comment by 0323pin** [comment]
@martin-olivier sounds reasonable to me. That's the way it worked on Void the first time it successfully started.

Might be a bit of a brain twist for some users, depending on _how you explain it_. But, I guess it, you know you don't want `systemd`, you should probably know how to handle this.

So yes, I think this is fine.

**Comment by martin-olivier** [comment]
Hello, I have added that information at the beginning of the [usage](https://github.com/martin-olivier/airgorah/wiki/Usage) documentation.

**Comment by 0323pin** [comment]
Nice, thanks.

Would you like to close this issue?
